### ISSUE TITLE
A little graphic issue when I open a file from menu

### ISSUE THREAD

**Issue by MathewFreddickRiddle** [CSMarckitus/Photoshop#10]
![Captura de pantalla de 2022-03-09 22-36-12](https://user-images.githubusercontent.com/70706948/157570199-6d0dfe89-8d6f-4a2b-a92a-45b3568233c5.png)
When I open a Photoshop file, this glitch appear, and it doesn't gone.
Also, if I open thought the menu bar, this _bug_ doesn't appear.

**Comment by CSMarckitus** [comment]
Hello,
Yes, I have the same bug like you. It's something that I can't fix, but I thing that it's a little bug that with the trick that you share of opening the file thought the menu it is not important and it has an easy solution.
Thank you very much for sharing your feedback!! 🙏
