### ISSUE TITLE
When I click in "open" in menu bar, or anything else, it doesn't pop up nothing

### ISSUE THREAD

**Issue by MathewFreddickRiddle** [CSMarckitus/Photoshop#11]
Hello, again!
I've reinstall _Photoshop_ on GNU/Linux (_elementary OS_), but when I click "open" or similar options in menu bar, nothing happens.
Any sollution?

**Comment by CSMarckitus** [comment]
Hello, 
Don't worry, it's a bug, but in another issue we discussed the solution to this: https://github.com/CSMarckitus/Photoshop/issues/9.
Try it and tell me in this issue if finally it works for you.
Thank a lot for your feedback!

**Comment by MathewFreddickRiddle** [comment]
Thanks!
It  Worked!

**Comment by CSMarckitus** [comment]
Weeeell!
Any problem you encounter let us know.
