### ISSUE TITLE
Cant quit app normally (freezes on quit)

### ISSUE THREAD

**Issue by XDM-Inc** [CSMarckitus/Photoshop#12]
whenever i quit the app it goes back to the welcome screen  and wont close unless you force quit

my specs
pop os 21.10 (ubuntu Debian based)
cpu: Ryzen 5950x
gpu: Radeon 6900 XT
64gb gskill ram
asus hero wifi motherboard

here is a log, i dont know if its the right kinda log but photoshop generated it
https://pastebin.com/zGqCUzFw

**Comment by CSMarckitus** [comment]
Hello ,
True, it happens to me, I'll try to solve it. I think the fault may be in the command I use to create the Photoshop shortcut.
Thanks for your feedback and I try to solve it.
