### ISSUE TITLE
Black Screen on startup

### ISSUE THREAD

**Issue by RoundTable99** [CSMarckitus/Photoshop#13]
I can use the menus in Photoshop 2020; change preferences, etc, but actually trying to use the program isn't an option. Have disabled 'start screen' already with no luck. If anyone has an idea on how to fix, let me know.

If it helps, I'm on archcraft linux

**Comment by RoundTable99** [comment]
I've now found a fix for the problem, so if anyone else has this issue, open a picture in photoshop, then restart the program and things should work from then on.

**Comment by Haelikor** [comment]
Just a sidenote until this project gets updated: if you actually let the Wine config stay Windows 7 instead of changing it to 10, you won't get the black screen / file browsing issues. 

Obv this has other problems but it's a side-solution. lol

**Comment by CSMarckitus** [comment]
Oh @Haelikor ,
That will help a lot of people who have the same problem.
Thanks for your feedback!

**Comment by CSMarckitus** [comment]
Hello @RoundTable99 ,
I'm surprised that I hadn't answered the issue.
Thank you very much for your feedback! Soon I will try to switch to a new version of Photoshop.

**Comment by RoundTable99** [comment]
Okay.
What version of Photoshop will you go with next? Because apart from the issue I mentioned - which I also fixed - nothing else has gone wrong for me :)

**Comment by CSMarckitus** [comment]
When I get around to it I will try to go to the most recent version of Photoshop, now is the 23.2.2 released on March 15, 2022.

**Comment by RoundTable99** [comment]
Alright then. Good luck :)On 6 Apr 2022 07:27, CSMarckitus ***@***.***> wrote:
When I get around to it I will try to go to the most recent version of Photoshop, now is the 23.2.2 released on March 15, 2022.

**Comment by CSMarckitus** [comment]
Hello @RoundTable99 ,
Finally I decided that I will try to make the same installer works for the latest version of Photoshop with English language native on 18/04/2022.

**Comment by RoundTable99** [comment]
Yay! I look forward to it 🙂On 12 Apr 2022 22:21, CSMarckitus ***@***.***> wrote:
Hello @RoundTable99 ,
Finally I decided that I will try to make the same installer works for the latest version of Photoshop with English language native on 18/04/2022!!
