### ISSUE TITLE
Save and save as not working 

### ISSUE THREAD

**Issue by magh2005** [CSMarckitus/Photoshop#14]
When I try to save as doesn't open any window to save file ):

**Comment by CSMarckitus** [comment]
Hello @magh2005 ,
Yes, we know that bug, you need to do File -> Export -> Export Layers to Files. This save every layer of your project into different files so if you have a project with many layers: 
You can export only 1 layer, then open the psd created with the 1 layer, copy paste the other layers and finally for save all the project only click in Save.
Thanks for your feedback!!

**Comment by magh2005** [comment]
> Hello @magh2005 , Yes, we know that bug, you need to do File -> Export -> Export Layers to Files. This save every layer of your project into different files so if you have a project with many layers: You can export only 1 layer, then open the psd created with the 1 layer, copy paste the other layers and finally for save all the project only click in Save. Thanks for your feedback!!

Hi , thanks for your help , I copy the photoshoot 2021 files installed on my windows in the photoshop 2020 folder installed with script and now everything works awesome and, save and save as works too 😄

**Comment by CSMarckitus** [comment]
Hello @magh2005 ,
Wooow, that's a very important step (the fact that the Phosothop 2021 works) if i can in one month I try to update Photoshop to the latest version possible.
And this time if I find that works, I will publish the English version.
Thanks for your feedback!!
