### ISSUE TITLE
GPU acceleration isn't working

### ISSUE THREAD

**Issue by myownfriend** [CSMarckitus/Photoshop#15]
I have a GTX 1070 so it's more than capable of being used for Photoshop but the Use Graphics Processor option is greyed out. Is this a known limitation or can I fix this?

**Comment by CSMarckitus** [comment]
Hello @myownfriend ,
Yes, that's a known limitation, at the moment it can't be corrected, so in 1 month I will try to test the version of Photoshop 2022 and if it works I will publish it.
Thanks for your feedback!
