### ISSUE TITLE
Problem installing on Manjaro (Arch)

### ISSUE THREAD

**Issue by gvladut** [CSMarckitus/Photoshop#2]
I tried running the installer under valgrind but it gave me the "Checking if the distribution is supported...The distribution you are using is not supported or cannot be recognized==108704==". I am not a programmer so I do not know how to modify the code to get it running, any chance for an update?

**Comment by CSMarckitus** [comment]
@gvladut Hello, finally can you try Photoshop on Manjaro? What will are the results?
If you do not answer me, I will close this discussion.
