### ISSUE TITLE
Ubuntu Ubuntu 20.04.4 LTS seg fault

### ISSUE THREAD

**Issue by EdHeller** [CSMarckitus/Photoshop#21]
1
Checking RAM...
✓ You have 15962MB of 2000MB
Checking CPU...
Segmentation fault (core dumped)

This looks kinda scary... 

Edit: the install worked fine though. The main screen is janky but it's semi functional in windowed mode.
Fixing the screen requires dragging it off the bottom of the desktop... sometimes ctrl+shift+win+B will work.

**Comment by CSMarckitus** [comment]
Hello @EdHeller ,
That error don't know why some people get the same error and other don't. Is related with how the system save info into variables.
This issue have a temporal solution, you need to install valgrind (in the case of Ubuntu you need to type sudo apt install valgrind) and execute the installer with valgrind:
valgrind ./Photoshop2020
Thanks for your feedback and I will try to fix it
