### ISSUE TITLE
lots of errors while installing

### ISSUE THREAD

**Issue by poltregeist** [CSMarckitus/Photoshop#22]
I am not going to pretend I know what went wrong, please help, I am still relatively new to linux. This is a copy of the console. 

Welcome to Photoshop CC v21 Linux Installer
Choose one of the following options:
1. Check if your computer meets the requirements to run Photoshop
2. Install Photoshop
3. Install Adobe Camera Raw v12
4. Configure Wine
5. Uninstall Photoshop
6. Exit the program
2
Do you have an Ubuntu or a Ubuntu based distro (if is other Debian based distro or Debian now write no)? [yes/no]: yes
Reading package lists... Done
Building dependency tree       
Reading state information... Done
wine64 is already the newest version (5.0-3ubuntu1).
wget is already the newest version (1.20.3-1ubuntu2).
The following packages were automatically installed and are no longer required:
  a11y-profile-manager-indicator adium-theme-ubuntu diffstat doc-base ethtool ettercap-common example-content folks-common gdebi gdebi-core geary
  gir1.2-appindicator3-0.1 gnome-system-log gucharmap ifupdown intltool-debian liba11y-profile-manager-0.1-0 liba11y-profile-manager-data libapt-pkg-perl
  libarchive-zip-perl libasync-mergepoint-perl libb-hooks-endofscope-perl libb-hooks-op-check-perl libcapture-tiny-perl libclass-method-modifiers-perl
  libclass-xsaccessor-perl libclone-perl libdevel-callchecker-perl libdevel-size-perl libdigest-bubblebabble-perl libdynaloader-functions-perl
  libemail-valid-perl libexporter-tiny-perl libfile-find-rule-perl libfl2 libfolks-eds25 libfolks25 libfont-ttf-perl libforms2 libfuture-perl libfwupdplugin1
  libgmime-3.0-0 libgucharmap-2-90-7 libimport-into-perl libio-async-loop-epoll-perl libio-async-perl libjson-maybexs-perl liblinux-epoll-perl
  liblist-compare-perl liblist-moreutils-perl libmodule-implementation-perl libmodule-runtime-perl libmoo-perl libmoox-aliases-perl libnamespace-clean-perl
  libnet-dns-perl libnet-dns-sec-perl libnet-domain-tld-perl libnet-ip-perl libnet1 libnumber-compare-perl libpackage-stash-perl libpackage-stash-xs-perl
  libparams-classify-perl libpath-tiny-perl libperl4-corelibs-perl libperlio-gzip-perl libreadonly-perl libref-util-perl libref-util-xs-perl
  librole-tiny-perl libsereal-decoder-perl libsereal-encoder-perl libsereal-perl libstrictures-perl libstruct-dumb-perl libsub-exporter-progressive-perl
  libsub-identify-perl libsub-quote-perl libtest-fatal-perl libtest-refcount-perl libtext-glob-perl libtext-levenshtein-perl libtype-tiny-perl
  libtype-tiny-xs-perl libunicode-utf8-perl libuuid-perl libvariable-magic-perl libwireshark13 libwiretap10 libwsutil11 libxml-writer-perl
  libyaml-libyaml-perl libyaml-tiny-perl libytnef0 libzeitgeist-1.0-1 light-themes lintian onboard onboard-common onboard-data overlay-scrollbar
  overlay-scrollbar-gtk2 patchutils ppa-purge pppconfig pppoeconf python3-pyudev t1utils ubuntu-artwork ubuntu-software unity-accessibility-profiles
  unity-lens-applications unity-lens-files unity-scopes-runner
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
--2022-04-12 02:24:47--  https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 896662 (876K) [text/plain]
Saving to: ‘winetricks’

winetricks                              100%[==============================================================================>] 875.65K  --.-KB/s    in 0.1s    

2022-04-12 02:24:47 (6.79 MB/s) - ‘winetricks’ saved [896662/896662]

Installing winetricks...Where do you want to install Photoshop (Absolute Route)?:
Example of route (realize that in the end it doesn't end with /): /home/your_username
/home/david
cat: /tmp/winetricks.deITpIwM/stdout.tmp: No such file or directory
rm: cannot remove '/tmp/winetricks.deITpIwM/stdout.tmp': No such file or directory
------------------------------------------------------
warning: Github down? version '' doesn't appear to be a valid version
------------------------------------------------------
Executing mkdir -p /home/david
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20220411-next - sha256sum: 59e8ea1a924fd74effd7fbdc63746e9b709f8f323f1dcbb1877454dbc0367014 with wine-5.0 (Ubuntu 5.0-3ubuntu1) and WINEARCH=win64
Executing w_do_call vcrun2019
Executing mkdir -p /home/david
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Executing load_vcrun2019 
------------------------------------------------------
warning: ucrtbase.dll is no longer included in vcrun2019. For details see: https://github.com/Winetricks/winetricks/issues/1770
------------------------------------------------------
Using native,builtin override for following DLLs: api-ms-win-crt-private-l1-1-0 api-ms-win-crt-conio-l1-1-0 api-ms-win-crt-heap-l1-1-0 api-ms-win-crt-locale-l1-1-0 api-ms-win-crt-math-l1-1-0 api-ms-win-crt-runtime-l1-1-0 api-ms-win-crt-stdio-l1-1-0 api-ms-win-crt-time-l1-1-0 atl140 concrt140 msvcp140 msvcp140_1 msvcp140_2 msvcr140 vcomp140 vcruntime140
Executing wine regedit C:\windows\Temp\override-dll.reg
Executing wine64 regedit C:\windows\Temp\override-dll.reg
Executing cd /home/david/.cache/winetricks/vcrun2019
Downloading https://aka.ms/vs/16/release/vc_redist.x86.exe to /home/david/.cache/winetricks/vcrun2019

04/12 02:25:13 [NOTICE] Downloading 1 item(s)

04/12 02:25:13 [NOTICE] CUID#7 - Redirecting to https://download.visualstudio.microsoft.com/download/pr/7e8edcf6-f2c1-41b1-a712-3f9cd8f58db4/4C6C420CF4CBF2C9C9ED476E96580AE92A97B2822C21329A2E49E8439AC5AD30/VC_redist.x86.exe

04/12 02:25:13 [ERROR] CUID#7 - Download aborted. URI=https://aka.ms/vs/16/release/vc_redist.x86.exe
Exception: [AbstractCommand.cc:403] errorCode=16 URI=https://download.visualstudio.microsoft.com/download/pr/7e8edcf6-f2c1-41b1-a712-3f9cd8f58db4/4C6C420CF4CBF2C9C9ED476E96580AE92A97B2822C21329A2E49E8439AC5AD30/VC_redist.x86.exe
  -> [RequestGroup.cc:760] errorCode=16 Download aborted.
  -> [AbstractDiskWriter.cc:224] errNum=13 errorCode=16 Failed to open the file /home/david/.cache/winetricks/vcrun2019/vc_redist.x86.exe, cause: Permission denied

04/12 02:25:13 [NOTICE] Download GID#0dc9dd4c2f05e52a not complete: /home/david/.cache/winetricks/vcrun2019/vc_redist.x86.exe

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
0dc9dd|ERR |       0B/s|/home/david/.cache/winetricks/vcrun2019/vc_redist.x86.exe

Status Legend:
(ERR):error occurred.

aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.
cat: /tmp/winetricks.deITpIwM/stdout.tmp: No such file or directory
rm: cannot remove '/tmp/winetricks.deITpIwM/stdout.tmp': No such file or directory
cat: /tmp/winetricks.deITpIwM/stdout.tmp: No such file or directory
rm: cannot remove '/tmp/winetricks.deITpIwM/stdout.tmp': No such file or directory
Executing cd /home/david/.cache/winetricks/vcrun2019
Downloading https://web.archive.org/web/2000/https://aka.ms/vs/16/release/vc_redist.x86.exe to /home/david/.cache/winetricks/vcrun2019

04/12 02:25:14 [NOTICE] Downloading 1 item(s)

04/12 02:25:14 [NOTICE] CUID#7 - Redirecting to https://web.archive.org/web/20190507042153/https://aka.ms/vs/16/release/vc_redist.x86.exe
[#f82440 0B/0B CN:1 DL:0B]                                                                                                                                    
04/12 02:25:16 [NOTICE] CUID#7 - Redirecting to https://web.archive.org/web/20190507042153/https://download.visualstudio.microsoft.com/download/pr/bc32da05-c8e2-44c3-9aa9-d09e192187e3/350440a80048a23581d6683b230dc58b/vc_redist.x86.exe

04/12 02:25:16 [NOTICE] CUID#7 - Redirecting to https://web.archive.org/web/20190507042207/https://download.visualstudio.microsoft.com/download/pr/bc32da05-c8e2-44c3-9aa9-d09e192187e3/350440a80048a23581d6683b230dc58b/vc_redist.x86.exe

04/12 02:25:16 [ERROR] CUID#7 - Download aborted. URI=https://web.archive.org/web/2000/https://aka.ms/vs/16/release/vc_redist.x86.exe
Exception: [AbstractCommand.cc:403] errorCode=16 URI=https://web.archive.org/web/20190507042207/https://download.visualstudio.microsoft.com/download/pr/bc32da05-c8e2-44c3-9aa9-d09e192187e3/350440a80048a23581d6683b230dc58b/vc_redist.x86.exe
  -> [RequestGroup.cc:760] errorCode=16 Download aborted.
  -> [AbstractDiskWriter.cc:224] errNum=13 errorCode=16 Failed to open the file /home/david/.cache/winetricks/vcrun2019/vc_redist.x86.exe, cause: Permission denied

04/12 02:25:16 [NOTICE] Download GID#f82440e24e9a3007 not complete: /home/david/.cache/winetricks/vcrun2019/vc_redist.x86.exe

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
f82440|ERR |       0B/s|/home/david/.cache/winetricks/vcrun2019/vc_redist.x86.exe

Status Legend:
(ERR):error occurred.

aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.
------------------------------------------------------
warning: Downloading https://web.archive.org/web/2000/https://aka.ms/vs/16/release/vc_redist.x86.exe failed
------------------------------------------------------
Click on Install to everything it asks for.Setting dark...Do you want to install Photoshop in your user or in all[only/all] ?: only
Installation completed successfully! Opening Photoshop CC v 21.0.2
Do you want to go back to the main menu?[n,y] 0009:fixme:reg:GetActiveProcessorGroupCount semi-stub, always returning 1
0009:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000022E150 1 C) semi-stub
0009:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000022DCE0 1 C) semi-stub
0009:err:module:LdrInitializeThunk "CRClient.dll" failed to initialize, aborting
0009:err:module:LdrInitializeThunk Initializing dlls for L"Z:\\home\\david\\PhotoshopCC\\Photoshop-CC\\Photoshop.exe" failed, status c0000005

**Comment by poltregeist** [comment]
upgraded to new version of ubuntu and the download worked

**Comment by cardboardcode** [comment]
> upgraded to new version of ubuntu and the download worked

Hi @poltregeist, may I know which new version of Ubuntu did you upgrade to? 

Encountered the same issue on **Ubuntu 20.04**.

**Comment by poltregeist** [comment]
Hi, it was from 20.04 to 22.04 lts.

**Comment by cardboardcode** [comment]
Noted. Thank you for responding so quickly :blush:
