### ISSUE TITLE
pops up and then freezes

### ISSUE THREAD

**Issue by gingergatto** [CSMarckitus/Photoshop#28]
Hey, I have an issue on one of the last stages, when the photoshop window pops up and then disappears, the terminal stays frozen on this command
`0258:err:sync:RtlpWaitForCriticalSection section 000000014C972598 "?" wait timed out in thread 0258, blocked by 0100, retrying (60 sec)
`

**Comment by CSMarckitus** [comment]
Hello @gingergatto ,
That seems a generic error of Wine, so althought this error appears, you tried to open Photoshop?
And you choose Wine with Windows 7?
