### ISSUE TITLE
Error after installation

### ISSUE THREAD

**Issue by RuiMinamino07** [CSMarckitus/Photoshop#29]
![Screenshot from 2022-05-21 11-15-39](https://user-images.githubusercontent.com/105979440/169657910-e3721ff3-558f-494d-8f96-d30a20c012c2.png)

![Screenshot from 2022-05-21 11-21-02](https://user-images.githubusercontent.com/105979440/169658175-acbe4481-a6bf-4196-af49-268623db0ea8.png)

I'm encountering this error CEPTHMLengine.exe after installation of Photoshop and since  this was related to Adobe itself so I wonder how this will be fixed. Thanks for the help in advance!

update: I cannot use export in any form. I'm using endevour OS if ever it was needed.

**Comment by CSMarckitus** [comment]
Hello @RuiMinamino07 ,
This error is strange, beacuse the installation of Photoshop I made is separate from other Adobe programs. You can open Photoshop or when this error shows you up?

**Comment by milkyskies** [comment]
Hello, I am getting the same error. Is there a way to fix?

**Comment by MuhmdAjeer** [comment]
@CSMarckitus Im facing this same issue.I have completed the installation without any errors.But when i launch the App it shows this popup and closes the app.

Is there any fix?

![Screenshot from 2023-07-03 23-27-33](https://github.com/CSMarckitus/Photoshop/assets/100233999/f6c93d9b-2ca0-42e0-bc70-9fa5cd1e697d)
