### ISSUE TITLE
Problem to install in Linux Mint 20.2 Cinnamon

### ISSUE THREAD

**Issue by WernerAUT** [CSMarckitus/Photoshop#3]
Hello,

i get an Memory Access Error message

```
Welcome to Photoshop CC v21 Linux Installer
Choose one of the following options:
1. Check if your computer meets the requirements to run Photoshop
2. Install Photoshop
3. Install Adobe Camera Raw v12
4. Configure Wine
5. Uninstall Photoshop
6. Exit the program
1
Checking RAM...
✓ You have 15929MB of 2000MB
Checking CPU...
Speicherzugriffsfehler (Speicherabzug geschrieben)
```

**Comment by CSMarckitus** [comment]
Hello, good morning from Spain.
I just checked the error, it is a problem that occurs in many distros (maybe it just works without problems on my computer).
But there is a solution. Install the valgrind program (in your case, as you have a Debian-based distribution), it is installed by typing in the terminal:
sudo apt-get install valgrind
Now delete all the downloaded files and start over:
git clone https://gitlab.com/csmarckitus1/photoshop.git
And then:
cd photoshop; make; valgrind ./Photoshop2020

I hope it works for you, I will be attentive to your reply !!
Thank you very much for your feedback.

**Comment by WernerAUT** [comment]
i tried that already before but without success :/

`Checking RAM...
✓ You have 15929MB of 2000MB
Checking CPU...
✓ You have a 64 bits CPU
X You don't have a 2GHz or more of CPU
Check screen...
✓ You have a good resolution
Checking GPU...
✓ You have enoguht VRAM
You have an nVidia GeForce GTX 1050 or equivalent or better?[n,y]: y
✓ Can install Photoshop
You have free more of 3GB on disk?[n,y]: y
✓ You have free space available
SUMMARY: 
X You do not meet the minimum requirements to install Photoshop X `

but for sure my CPU is faster then 2 GHz lol
and when i try to install with valgrind i get this

`*** stack smashing detected ***: terminated
==49009== 
==49009== Process terminating with default action of signal 6 (SIGABRT)
==49009==    at 0x48AE18B: raise (raise.c:51)
==49009==    by 0x488D858: abort (abort.c:79)
==49009==    by 0x48F83ED: __libc_message (libc_fatal.c:155)
==49009==    by 0x499AB49: __fortify_fail (fortify_fail.c:26)
==49009==    by 0x499AB15: __stack_chk_fail (stack_chk_fail.c:24)
==49009==    by 0x109D70: install_photoshop (Installer.c:138)
==49009==    by 0x1094B7: main (Photoshop.c:47)
Checking if the distribution is supported...The distribution you are using is not supported or cannot be recognized==49009== 
==49009== HEAP SUMMARY:
==49009==     in use at exit: 0 bytes in 0 blocks
==49009==   total heap usage: 18 allocs, 18 frees, 25,095 bytes allocated
==49009== 
==49009== All heap blocks were freed -- no leaks are possible
==49009== 
==49009== For lists of detected and suppressed errors, rerun with: -s
==49009== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
Abgebrochen (Speicherabzug geschrieben)
`

**Comment by WernerAUT** [comment]
the new version works for me now, also without valgrind.
Would be nice if you could add english and german to locale ;)
But i have also another issue that i can't use open it doesn't show anything
