### ISSUE TITLE
interface not responding

### ISSUE THREAD

**Issue by Abdulrazakmus** [CSMarckitus/Photoshop#30]
i just installed photoshop today but when am trying to open new workspace the enterface that appear doesnot respond (i cant see description fonts)
![Screenshot from 2022-05-22 07-42-48](https://user-images.githubusercontent.com/97451845/169693887-5c21cc55-c993-4822-a6f3-a433914d1f9f.png)

**Comment by CSMarckitus** [comment]
Hello @Abdulrazakmus ,
Yeah, I think this error appears to all of us, if you want to create a workspace or simply a new project or psd file you need to do:
File -> Export -> Export Layers to Files and then select the format that you want to save your project, by default is PSD.
Then the project will be saved and you can use the Save function without problem.
If you want to Export your project into a JPG or other format, the solution is:
File -> Export -> Save for web.
Thanks for your feedback and tell me if it worked for you
