### ISSUE TITLE
mkdir: cannot create directory ‘/home/artrus’: Permission denied

### ISSUE THREAD

**Issue by NeuHix** [CSMarckitus/Photoshop#37]
I'm running Fedora 36 Wayland and Wine 7.0 
During installation when it asks to provide directory but it fails to create directory and says **permission denied.**
How can I give it permission or somehow use `sudo` .  In normal terminal, I'm able to create directories without giving any administrative privilages.  
### This is the error i get: 
```
Example of route (realize that in the end it doesn't end with /): /home/your_username
/home/artrus
mkdir: cannot create directory ‘/home/artrus/PhotoshopCC’: No such file or directory
Executing mkdir -p /home/artrus
mkdir: cannot create directory ‘/home/artrus’: Permission denied
------------------------------------------------------
warning: Note: command mkdir -p /home/artrus returned status 1. Aborting.
------------------------------------------------------
wine: chdir to /home/artrus/PhotoshopCC : No such file or directory
Can't open user.reg file.Click on Install to everything it asks for.Setting dark
```

**Comment by NeuHix** [comment]
I gave the permission.
First made the terminal **root** by `sudo su`  and all gone well.

**Comment by CSMarckitus** [comment]
Hi @NeuHix,
Yeah, it's true, this error is about Linux usage.But anyway I'm thinking that if you are executing the terminal as the user in with you want to write a folder, it needs to be done without sudo permission. Maybe that is related to the executable file permissions.

**Comment by NeuHix** [comment]
Hi @CSMarckitus  
when I made the terminal root by `sudo su` ,  then there was no issue and it was able to create directories.  **But everything got stored in my root's directories.**
