### ISSUE TITLE
Illustrator

### ISSUE THREAD

**Issue by webaseo** [CSMarckitus/Photoshop#4]
Hello, aren't you planning to make a similar script for Illustrator? Thank you, it would be very much appreciated:)

**Comment by CSMarckitus** [comment]
Hi, I'm sorry for answering later. 
Currently I don't have much free time, but I have been looking and yes, as soon as I can I will post it and comment on it in this discussion. The version that I see possible is: Adobe Illustrator CC 2021 version 25.1.0.90 (according to the following report of WIneHQ DB: https://appdb.winehq.org/objectManager.php?sClass=version&iId=40071)
Thanks for your feedback.

**Comment by b3pio** [comment]
Thanks for you hard work with this project. Also, perhaps you can consider InDesign after Illustrator? I would love to see the Affinity suite come to Linux over adobe but it seems Affinity Photo/Designer/Publisher is at 'garbage' status with Wine at the present..

**Comment by CSMarckitus** [comment]
Hello @b3pio ,
After some time, now I see that someone called [MiMillieuh](https://github.com/MiMillieuh) has done the script for install Illustrator v21.
If you want, you can check it here: https://github.com/MiMillieuh/Illustrator-CC-2021-Linux.
Personally I don't test it, but seems good.

I hope this can help you.
