### ISSUE TITLE
'Can't open user.reg file'

### ISSUE THREAD

**Issue by Maxsuragi** [CSMarckitus/Photoshop#41]
Seems I can get to the end of the installation until I'm thrown this error, followed by 'Click on Install to everything it asks for.Setting dark...'
From what I understand this is the final question and you should usually be able to answer. Except the installation just terminates here.

'Can't open user.reg file.Click on Install to everything it asks for.Setting dark...'

EDIT: Sorry for wasting time here, after a few fresh install attempts it seems to have fixed itself.

**Comment by CSMarckitus** [comment]
Hello @Maxsuragi ,
Don't worry, thanks a lot for share your feedback to others, sometimes all of your errors are based on missing of permissions or a specific error in system configuration.
