### ISSUE TITLE
DXVK files in home directory

### ISSUE THREAD

**Issue by HugoPlacer** [CSMarckitus/Photoshop#43]
When I launch Photoshop, it creates a bunch of DXVK cache files in my home folder.
I find a workaround that consists in modify the photoshop.desktop to include at the beginning of the line: "cd /"directory where you want to store the cache (in my case in the wineprefix folder)"/;

My home folder:
![imagen](https://user-images.githubusercontent.com/69766683/194363684-10f18091-4fd2-4bd0-b791-6d2edde2f332.png)

My case Workaround:

![imagen](https://user-images.githubusercontent.com/69766683/194363835-aa7f4b5c-78f7-4eb5-a1f9-f30560c45c2a.png)

**Comment by CSMarckitus** [comment]
Hello @HugoPlacer ,
I'm also from Barcelona. Yes, the script also for me was creating DXVK files on home directory.
Now among other things that I've change, this is fixed. 
I push the changes, so anyone  can download it improved.

Thanks a lot for your feedback and solution, I appreciate a lot!
If you want to contact with me for some thing: martajuglares@gmail.com
