### ISSUE TITLE
Default Language

### ISSUE THREAD

**Issue by DashCruft** [CSMarckitus/Photoshop#5]
This works pretty nicely.

However, I suggest putting the default language of the installed photoshop, to US English instead of the existing language.

Otherwise, neat idea and work!

**Comment by rattkin** [comment]
How did you change the language?

**Comment by DashCruft** [comment]
I found this tutorial which helps to solve that and it works:

https://youtu.be/wTX2IfbP_ZQ

**Comment by CSMarckitus** [comment]
Hello, yeah, the solution that propose @DashCruft seems to work perfectly:

> I found this tutorial which helps to solve that and it works:
> 
> https://youtu.be/wTX2IfbP_ZQ

I have not yet been able to test the solution (currently I don't have much free time) but as soon as I can I will try it and I will tell you the result.
Thanks @DashCruft for your solution!

**Comment by rattkin** [comment]
Deleted the file tw10428_*
